/* generated by scripts/gen-sw.mjs — 手動編集しないこと */
"use strict";

const CACHE_NAME = "nou-denchi-781808350b52";
const BASE_PATH = "/nou-denchi";
const ASSETS = [
  "/nou-denchi/404.html",
  "/nou-denchi/404/index.html",
  "/nou-denchi/__next.__PAGE__.txt",
  "/nou-denchi/__next._full.txt",
  "/nou-denchi/__next._head.txt",
  "/nou-denchi/__next._index.txt",
  "/nou-denchi/__next._tree.txt",
  "/nou-denchi/_next/static/aC69GxA6umGdoSlLS4TL6/_buildManifest.js",
  "/nou-denchi/_next/static/aC69GxA6umGdoSlLS4TL6/_clientMiddlewareManifest.js",
  "/nou-denchi/_next/static/aC69GxA6umGdoSlLS4TL6/_ssgManifest.js",
  "/nou-denchi/_next/static/chunks/05-c3ty_6dwfk.js",
  "/nou-denchi/_next/static/chunks/0cz1d0mv5g_q7.js",
  "/nou-denchi/_next/static/chunks/0f5tlb1ikrrrg.css",
  "/nou-denchi/_next/static/chunks/0fx16q43cru5t.js",
  "/nou-denchi/_next/static/chunks/0oohev6_eifiv.js",
  "/nou-denchi/_next/static/chunks/1-8s9_t85wwr4.js",
  "/nou-denchi/_next/static/chunks/14ipmiotzurw_.js",
  "/nou-denchi/_next/static/chunks/1r3r4sa5td8o7.js",
  "/nou-denchi/_next/static/chunks/2-3onunkwrki2.js",
  "/nou-denchi/_next/static/chunks/2-i11ueqanae9.js",
  "/nou-denchi/_next/static/chunks/25o46h8mdjlrg.js",
  "/nou-denchi/_next/static/chunks/261y1hxfsqgcm.js",
  "/nou-denchi/_next/static/chunks/26wq10aya-7r-.js",
  "/nou-denchi/_next/static/chunks/27jktro2p5rq9.js",
  "/nou-denchi/_next/static/chunks/2cefqndozczdw.js",
  "/nou-denchi/_next/static/chunks/2dhu89_d5v3x0.js",
  "/nou-denchi/_next/static/chunks/2ecb7tysdp__c.js",
  "/nou-denchi/_next/static/chunks/2ftle-pa-liq0.js",
  "/nou-denchi/_next/static/chunks/2fyxxrb9pz58j.js",
  "/nou-denchi/_next/static/chunks/2y9soa0s1sw4i.js",
  "/nou-denchi/_next/static/chunks/3tnd5w6h5p8k9.js",
  "/nou-denchi/_next/static/chunks/40zlv0m65ur_d.js",
  "/nou-denchi/_next/static/chunks/44sej6gmf0mz-.js",
  "/nou-denchi/_next/static/chunks/turbopack-2_9xjhnyfnnf9.js",
  "/nou-denchi/_next/static/media/4fa387ec64143e14-s.2tuy5pz7dlieh.woff2",
  "/nou-denchi/_next/static/media/53b9e256198e5412-s.390ncx5urfkfu.woff2",
  "/nou-denchi/_next/static/media/5ce348bf30bf5439-s.31988l_ccedte.woff2",
  "/nou-denchi/_next/static/media/6306c77e7c8268e4-s.2dbetqa9o8jxf.woff2",
  "/nou-denchi/_next/static/media/7178b3e590c64307-s.21jp631_3pja2.woff2",
  "/nou-denchi/_next/static/media/797e433ab948586e-s.p.0r6juujl39pe6.woff2",
  "/nou-denchi/_next/static/media/7d817b4c03b0c5f1-s.1uyisp29ctx0d.woff2",
  "/nou-denchi/_next/static/media/8a480f0b521d4e75-s.1qq4vpdcun5oj.woff2",
  "/nou-denchi/_next/static/media/apple-icon.2m0-9e960z48z.png",
  "/nou-denchi/_next/static/media/bbc41e54d2fcbd21-s.1rgnod-3esatf.woff2",
  "/nou-denchi/_next/static/media/caa3a2e1cccd8315-s.p.0wgildi0cnwt9.woff2",
  "/nou-denchi/_next/static/media/favicon.2vob68tjqpejf.ico",
  "/nou-denchi/_next/static/media/fef07dbb0973bf53-s.3p2_lha1f2xer.woff2",
  "/nou-denchi/_next/static/media/icon.25v5zl6k-frva.png",
  "/nou-denchi/_not-found/__next._full.txt",
  "/nou-denchi/_not-found/__next._head.txt",
  "/nou-denchi/_not-found/__next._index.txt",
  "/nou-denchi/_not-found/__next._not-found.__PAGE__.txt",
  "/nou-denchi/_not-found/__next._not-found.txt",
  "/nou-denchi/_not-found/__next._tree.txt",
  "/nou-denchi/_not-found/index.html",
  "/nou-denchi/_not-found/index.txt",
  "/nou-denchi/apple-icon.png",
  "/nou-denchi/art/button-measure.webp",
  "/nou-denchi/art/gauge.webp",
  "/nou-denchi/art/holo-brain.webp",
  "/nou-denchi/art/metal-disc.webp",
  "/nou-denchi/art/water-bg.webp",
  "/nou-denchi/boost/__next._full.txt",
  "/nou-denchi/boost/__next._head.txt",
  "/nou-denchi/boost/__next._index.txt",
  "/nou-denchi/boost/__next._tree.txt",
  "/nou-denchi/boost/__next.boost.__PAGE__.txt",
  "/nou-denchi/boost/__next.boost.txt",
  "/nou-denchi/boost/index.html",
  "/nou-denchi/boost/index.txt",
  "/nou-denchi/brand/logo-alpha.png",
  "/nou-denchi/brand/logo.png",
  "/nou-denchi/favicon.ico",
  "/nou-denchi/games/banner-boost.webp",
  "/nou-denchi/games/banner-relax.webp",
  "/nou-denchi/games/banner-tr-math.webp",
  "/nou-denchi/games/banner-tr-pvt.webp",
  "/nou-denchi/games/banner-tr-stroop.webp",
  "/nou-denchi/games/banner-treota.webp",
  "/nou-denchi/history/__next._full.txt",
  "/nou-denchi/history/__next._head.txt",
  "/nou-denchi/history/__next._index.txt",
  "/nou-denchi/history/__next._tree.txt",
  "/nou-denchi/history/__next.history.__PAGE__.txt",
  "/nou-denchi/history/__next.history.txt",
  "/nou-denchi/history/index.html",
  "/nou-denchi/history/index.txt",
  "/nou-denchi/icon.png",
  "/nou-denchi/icons/icon-192.png",
  "/nou-denchi/icons/icon-512.png",
  "/nou-denchi/icons/icon-maskable-512.png",
  "/nou-denchi/index.html",
  "/nou-denchi/index.txt",
  "/nou-denchi/manifest.webmanifest",
  "/nou-denchi/measure/__next._full.txt",
  "/nou-denchi/measure/__next._head.txt",
  "/nou-denchi/measure/__next._index.txt",
  "/nou-denchi/measure/__next._tree.txt",
  "/nou-denchi/measure/__next.measure.__PAGE__.txt",
  "/nou-denchi/measure/__next.measure.txt",
  "/nou-denchi/measure/index.html",
  "/nou-denchi/measure/index.txt",
  "/nou-denchi/onboarding/__next._full.txt",
  "/nou-denchi/onboarding/__next._head.txt",
  "/nou-denchi/onboarding/__next._index.txt",
  "/nou-denchi/onboarding/__next._tree.txt",
  "/nou-denchi/onboarding/__next.onboarding.__PAGE__.txt",
  "/nou-denchi/onboarding/__next.onboarding.txt",
  "/nou-denchi/onboarding/index.html",
  "/nou-denchi/onboarding/index.txt",
  "/nou-denchi/privacy/index.html",
  "/nou-denchi/relax/__next._full.txt",
  "/nou-denchi/relax/__next._head.txt",
  "/nou-denchi/relax/__next._index.txt",
  "/nou-denchi/relax/__next._tree.txt",
  "/nou-denchi/relax/__next.relax.__PAGE__.txt",
  "/nou-denchi/relax/__next.relax.txt",
  "/nou-denchi/relax/index.html",
  "/nou-denchi/relax/index.txt",
  "/nou-denchi/result/__next._full.txt",
  "/nou-denchi/result/__next._head.txt",
  "/nou-denchi/result/__next._index.txt",
  "/nou-denchi/result/__next._tree.txt",
  "/nou-denchi/result/__next.result.__PAGE__.txt",
  "/nou-denchi/result/__next.result.txt",
  "/nou-denchi/result/index.html",
  "/nou-denchi/result/index.txt",
  "/nou-denchi/settings/__next._full.txt",
  "/nou-denchi/settings/__next._head.txt",
  "/nou-denchi/settings/__next._index.txt",
  "/nou-denchi/settings/__next._tree.txt",
  "/nou-denchi/settings/__next.settings.__PAGE__.txt",
  "/nou-denchi/settings/__next.settings.txt",
  "/nou-denchi/settings/index.html",
  "/nou-denchi/settings/index.txt",
  "/nou-denchi/training/__next._full.txt",
  "/nou-denchi/training/__next._head.txt",
  "/nou-denchi/training/__next._index.txt",
  "/nou-denchi/training/__next._tree.txt",
  "/nou-denchi/training/__next.training.__PAGE__.txt",
  "/nou-denchi/training/__next.training.txt",
  "/nou-denchi/training/index.html",
  "/nou-denchi/training/index.txt",
  "/nou-denchi/training/math/__next._full.txt",
  "/nou-denchi/training/math/__next._head.txt",
  "/nou-denchi/training/math/__next._index.txt",
  "/nou-denchi/training/math/__next._tree.txt",
  "/nou-denchi/training/math/__next.training.math.__PAGE__.txt",
  "/nou-denchi/training/math/__next.training.math.txt",
  "/nou-denchi/training/math/__next.training.txt",
  "/nou-denchi/training/math/index.html",
  "/nou-denchi/training/math/index.txt",
  "/nou-denchi/training/pvt/__next._full.txt",
  "/nou-denchi/training/pvt/__next._head.txt",
  "/nou-denchi/training/pvt/__next._index.txt",
  "/nou-denchi/training/pvt/__next._tree.txt",
  "/nou-denchi/training/pvt/__next.training.pvt.__PAGE__.txt",
  "/nou-denchi/training/pvt/__next.training.pvt.txt",
  "/nou-denchi/training/pvt/__next.training.txt",
  "/nou-denchi/training/pvt/index.html",
  "/nou-denchi/training/pvt/index.txt",
  "/nou-denchi/training/stroop/__next._full.txt",
  "/nou-denchi/training/stroop/__next._head.txt",
  "/nou-denchi/training/stroop/__next._index.txt",
  "/nou-denchi/training/stroop/__next._tree.txt",
  "/nou-denchi/training/stroop/__next.training.stroop.__PAGE__.txt",
  "/nou-denchi/training/stroop/__next.training.stroop.txt",
  "/nou-denchi/training/stroop/__next.training.txt",
  "/nou-denchi/training/stroop/index.html",
  "/nou-denchi/training/stroop/index.txt"
];

// install: 全アセットを precache(小規模アプリのため全量)+ 即時有効化
self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await cache.addAll(ASSETS.map((u) => new Request(u, { cache: "reload" })));
      await self.skipWaiting();
    })()
  );
});

// activate: 旧キャッシュ削除 + 既存クライアントの即時制御
self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => n.startsWith("nou-denchi-") && n !== CACHE_NAME)
          .map((n) => caches.delete(n))
      );
      await self.clients.claim();
    })()
  );
});

// fetch: 同一オリジンGETのみ処理。cache-first。
// ナビゲーションは 完全一致 → パス+index.html → /index.html の順にフォールバック
// (trailingSlash 構成のため /path/ は /path/index.html として precache されている)。
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(respond(request, url));
});

async function respond(request, url) {
  const cache = await caches.open(CACHE_NAME);
  const candidates = [url.pathname];
  if (request.mode === "navigate") {
    candidates.push(
      url.pathname.endsWith("/")
        ? url.pathname + "index.html"
        : url.pathname + "/index.html"
    );
    candidates.push(BASE_PATH + "/index.html");
  }
  for (const pathname of candidates) {
    const cached = await cache.match(pathname, { ignoreSearch: true });
    if (cached) return cached;
  }
  // キャッシュ外はネットワークへ(失敗時は何もしない=エラーレスポンス)
  try {
    return await fetch(request);
  } catch {
    return Response.error();
  }
}
