// Service Worker 生成スクリプト(要件§7 完全オフライン測定 MUST)。
// next build(output:'export')後の out/ を再帰走査し、全アセットを precache する
// out/sw.js を生成する。postbuild として自動実行される。
// 検証用に環境変数 OUT_DIR で対象ディレクトリを差し替え可能(デフォルト <project>/out)。
import { createHash } from "node:crypto";
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.resolve(process.env.OUT_DIR || path.join(root, "out"));

if (!existsSync(outDir)) {
  console.error(`gen-sw: out ディレクトリが見つかりません: ${outDir}`);
  console.error("先に next build を実行してください(通常は postbuild で自動実行)。");
  process.exit(1);
}

/** @param {string} dir @returns {string[]} 絶対パスのファイル一覧 */
function walk(dir) {
  const files = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walk(full));
    } else if (entry.isFile()) {
      files.push(full);
    }
  }
  return files;
}

// サブパス配信(GitHub Pages 等)対応: next build と同じ NEXT_PUBLIC_BASE_PATH を参照
const basePath = (process.env.NEXT_PUBLIC_BASE_PATH || "").replace(/\/+$/, "");

const assets = walk(outDir)
  .map((f) => path.relative(outDir, f).split(path.sep).join("/"))
  .filter((f) => f !== "sw.js") // sw.js 自身は precache しない
  .filter((f) => !f.split("/").includes(".DS_Store")) // macOS ゴミファイル除外
  .sort()
  .map((f) => encodeURI(basePath + "/" + f));

// キャッシュ名はアセットリストのsha256短縮ハッシュ入り(内容が変わればキャッシュも切替わる)
const hash = createHash("sha256")
  .update(JSON.stringify(assets))
  .digest("hex")
  .slice(0, 12);
const cacheName = `nou-denchi-${hash}`;

const sw = `/* generated by scripts/gen-sw.mjs — 手動編集しないこと */
"use strict";

const CACHE_NAME = ${JSON.stringify(cacheName)};
const BASE_PATH = ${JSON.stringify(basePath)};
const ASSETS = ${JSON.stringify(assets, null, 2)};

// install: 全アセットを precache(小規模アプリのため全量)+ 即時有効化
self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await cache.addAll(ASSETS.map((u) => new Request(u, { cache: "reload" })));
      await self.skipWaiting();
    })()
  );
});

// activate: 旧キャッシュ削除 + 既存クライアントの即時制御
self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((n) => n.startsWith("nou-denchi-") && n !== CACHE_NAME)
          .map((n) => caches.delete(n))
      );
      await self.clients.claim();
    })()
  );
});

// fetch: 同一オリジンGETのみ処理。cache-first。
// ナビゲーションは 完全一致 → パス+index.html → /index.html の順にフォールバック
// (trailingSlash 構成のため /path/ は /path/index.html として precache されている)。
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;
  event.respondWith(respond(request, url));
});

async function respond(request, url) {
  const cache = await caches.open(CACHE_NAME);
  const candidates = [url.pathname];
  if (request.mode === "navigate") {
    candidates.push(
      url.pathname.endsWith("/")
        ? url.pathname + "index.html"
        : url.pathname + "/index.html"
    );
    candidates.push(BASE_PATH + "/index.html");
  }
  for (const pathname of candidates) {
    const cached = await cache.match(pathname, { ignoreSearch: true });
    if (cached) return cached;
  }
  // キャッシュ外はネットワークへ(失敗時は何もしない=エラーレスポンス)
  try {
    return await fetch(request);
  } catch {
    return Response.error();
  }
}
`;

writeFileSync(path.join(outDir, "sw.js"), sw);
console.log(
  `gen-sw: ${path.join(outDir, "sw.js")} を生成 (assets=${assets.length}, cache=${cacheName})`
);
